[package]
name = "tg-prompt"
version = "0.1.0"
authors = ["lucky"]
edition = "2018"

[dependencies]
argh = "0.1"
teloxide = "0.4"
tokio = { version =  "1.3", features = ["rt-multi-thread", "macros"] }
